name: focusguard
description: "A premium, high-performance focus shield built with Flutter, featuring advanced app/web blocking and a sleek midnight aesthetic for deep productivity."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  installed_apps: ^2.1.1
  flutter_background_service: ^5.1.0
  go_router: ^17.1.0
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  uuid: ^4.0.0
  url_launcher: ^6.3.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/dev.json